name: Auto Commit Sholat

on:
  schedule:
    - cron: '0 5 * * *'
    - cron: '0 12 * * *'
    - cron: '0 15 * * *'
    - cron: '0 18 * * *'
    - cron: '0 19 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get Prayer Times from Aladhan API
      id: prayer_times
      run: |
        sudo apt-get update
        sudo apt-get install -y curl jq

        CITY="Pekanbaru"
        COUNTRY="Indonesia"
        METHOD=2

        response=$(curl -s "https://api.aladhan.com/v1/timingsByCity?city=${CITY}&country=${COUNTRY}&method=${METHOD}")

        fajr=$(echo $response | jq -r '.data.timings.Fajr')
        dhuhr=$(echo $response | jq -r '.data.timings.Dhuhr')
        asr=$(echo $response | jq -r '.data.timings.Asr')
        maghrib=$(echo $response | jq -r '.data.timings.Maghrib')
        isha=$(echo $response | jq -r '.data.timings.Isha')

        echo "Subuh: $fajr" > prayer_times.txt
        echo "Dzuhur: $dhuhr" >> prayer_times.txt
        echo "Asar: $asr" >> prayer_times.txt
        echo "Maghrib: $maghrib" >> prayer_times.txt
        echo "Isya: $isha" >> prayer_times.txt

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Pull latest changes
      run: |
        git pull origin main --rebase

    - name: Update README.md with Prayer Times
      run: |
        echo "" >> README.md
        echo "### Sholat Times Update - $(date '+%Y-%m-%d %H:%M:%S')" >> README.md
        cat prayer_times.txt >> README.md

    - name: Commit and Push changes
      run: |
        git add README.md
        git commit -m "Auto commit: Update Waktu Sholat" --allow-empty
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main
